### ISSUE TITLE
支持osx么? ImportError: cannot import name epoll

### ISSUE THREAD

**Issue by jdlindu** [mengskysama/BurstLink#1]
➜  burstLink  python local.py
Traceback (most recent call last):
  File "local.py", line 25, in <module>
    from twisted.internet import epollreactor
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/twisted/internet/epollreactor.py", line 16, in <module>
    from select import epoll, EPOLLHUP, EPOLLERR, EPOLLIN, EPOLLOUT
ImportError: cannot import name epoll

能支持osx么

**Comment by daimajia** [comment]
+1

**Comment by mengskysama** [comment]
早上已经改过了，你可以试试，不过我的提供的2333似乎因为流量过大被审查限速了u2b无法使用。

**Comment by daimajia** [comment]
@mengskysama  Cool

**Comment by jdlindu** [comment]
➜  BurstLink git:(master) ✗ python local.py
Traceback (most recent call last):
  File "local.py", line 25, in <module>
    from twisted.internet import pollreactor
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/twisted/internet/pollreactor.py", line 18, in <module>
    from select import error as SelectError, poll
ImportError: cannot import name poll

环境: 
osx 10.10.1
python 2.7.6
Twisted (13.2.0)

**Comment by daimajia** [comment]
依旧是这个

**Comment by jdlindu** [comment]
没更新了么?

**Comment by mengskysama** [comment]
准备换掉框架.抽空写

**Comment by jdlindu** [comment]
期待,tks
